---
- name: clojurecup user
  user: name=clojurecup comment="Clojure Cup Judges" home=/home/clojurecup

- name: ensure clojurecup .ssh dir
  file: path=/home/clojurecup/.ssh owner=clojurecup mode=0700 state=directory

- name: clojurecup authorized_keys
  copy: src=authorized_keys/clojurecup dest=/home/clojurecup/.ssh/authorized_keys owner=clojurecup mode=0600

- name: dkr user
  user: name=dkr comment="Docker" group=docker home=/home/dkr

- name: ensure dkr .ssh dir
  file: path=/home/dkr/.ssh owner=dkr mode=0700 state=directory

- name: jenkins dkr ssh key
  copy: src=authorized_keys/dkr dest=/home/dkr/.ssh/authorized_keys owner=dkr mode=0600

- name: docker-py
  pip: name=docker-py

- name: docker nginx autoproxy
  docker: ports=80:80 image=colinrymer/nginx-proxy volumes=/var/run/docker.sock:/tmp/docker.sock state=running
  #docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock -t jwilder/nginx-proxy

- name: docker datomic-free
  docker: name=datomic image=tauho/datomic-free:0.9.4699 state=running

- name: docker tranjlater
  docker: name="{{ app_container_name }}" image="{{ app_image_name }}:{{ app_tag }}"

- name: deploy script
  template: src=deploy.j2 dest=/home/dkr/deploy.sh owner=dkr group=docker mode=0700
